settings:
  title: 'Stato dei servizi'
  url: 'https://status-page.ricaricaincasa.it' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 20 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Tutti i sistemi sono operativi'
  notAllmonitorsOperational: 'Non tutti i sistemi sono operativi'
  monitorLabelOperational: 'Operativo'
  monitorLabelNotOperational: 'Non operativo'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'Tutto ok'
  dayInHistogramNotOperational: ' Incidenti' # xx incident(s) recorded

monitors:
  - id: www # unique identifier
    name: ricaricaincasa.it
    description: 'Sito principale' # default=empty
    url: 'https://ricaricaincasa.it/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: api
    name: api.ricaricaincasa.it
    description: 'API server'
    url: 'https://api.ricaricaincasa.it'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
